---
- name: open a change request
  hosts: localhost
  vars:
    change_request:
      severity: 2
      priority: 2
      description: Automated Azure Provisioning
      justification: Ansible Triggered
      implementation_plan: Updated by Red Hat AAP
      risk_impact_analysis: Changes are made automatically based on approved changes
      test_plan: Run synthetic validation tests post-deployment
      short_description: Automated Azure Provisioning
  tasks:
    - name: Create a change request
      snow_record:
        state: present
        table: change_request
        username: "{{ snow_credentials.username | default(snow_username, true)}}"
        password: "{{ snow_credentials.password | default(snow_password, true)}}"
        instance: "{{ snow_credentials.instance | default(snow_instance, true)}}"
        data:
          severity: "{{ change_request.severity }}"
          priority: "{{ change_request.priority }}"
          short_description: "{{ change_request.short_description }}"
          implementation_plan: "{{ change_request.implementation_plan }}"
          justification: "{{ change_request.justification }}"
          description: "{{ change_request.description }}"
          risk_impact_analysis: "{{ change_request.risk_impact_analysis }}"
          test_plan: "{{ change_request.test_plan }}"
          start_date: "{{ ansible_date_time.iso8601 }}"
      register: new_incident

    - debug:
        var: new_incident.record
